name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Client
      run: cd client && npm i
    - name: Install Server
      run: cd server && npm i
    - name: Run client tests
      run: cd client && npm run test
    - name: Run server tests
      run: cd server && npm run test